#!/bin/sh

uci set network.lan.ipaddr='192.168.9.254'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.9.1'
uci -q delete network.lan.dns
uci add_list network.lan.dns='192.168..53'
uci add_list network.lan.dns='223.5.5.5'
uci set network.lan.delegate='0'
uci commit network

uci set dropbear.main.enable='1'
uci set dropbear.main.PasswordAuth='on'
uci set dropbear.main.RootPasswordAuth='on'
uci set dropbear.main.Port='22'
uci set dropbear.main.Interface='lan'
uci commit dropbear

# Keep first boot credential-free and force LuCI/console users to set a password.
passwd -d root 2>/dev/null || sed -i 's#^root:[^:]*:#root::#' /etc/shadow

/etc/init.d/network restart
/etc/init.d/dropbear restart

exit 0
